name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Setup maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
        
    - name: Build project
      run: mvn clean package
    
    - name: Build and push to Docker Hub
      run: docker build . --file Dockerfile --tag my-recipe-book-api:latest
